CREATE TABLE KHOA
(
	MAKHOA varchar2(4) PRIMARY KEY,
	TENKHOA varchar2(40),
	NGTLAP date,
	TRGKHOA char(4)
)

CREATE TABLE MONHOC
(
	MAMH varchar2(10) PRIMARY KEY,
	TENMH varchar2(40),
	TCLT int,
	TCTH int,
	MAKHOA varchar2(4) 
)
ALTER TABLE MONHOC ADD
CONSTRAINT FK_MH_KH FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);

CREATE TABLE DIEUKIEN
(
	MAMH varchar2(10) NOT NULL,
	MAMH_TRUOC varchar2(10) NOT NULL
)
ALTER TABLE DIEUKIEN ADD
CONSTRAINT PK_DK PRIMARY KEY (MAMH, MAMH_TRUOC);
ALTER TABLE DIEUKIEN ADD
CONSTRAINT FK_DK1 FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);
ALTER TABLE DIEUKIEN ADD
CONSTRAINT FK_DK2 FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH);

CREATE TABLE GIAOVIEN 
(
	MAGV char(4) PRIMARY KEY,
	HOTEN varchar2(40),
	HOCVI varchar2(10),
	HOCHAM varchar2(10),
	GIOITINH varchar2(3),
	NGSINH date,
	NGVL date,
	HESO numeric(4,2),
	MUCLUONG int,
	MAKHOA varchar2(4)
)

ALTER TABLE GIAOVIEN ADD
CONSTRAINT FK_GV_KH FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);

ALTER TABLE KHOA ADD
CONSTRAINT FK_K FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV);

CREATE TABLE LOP
(
	MALOP char(3) PRIMARY KEY,
	TENLOP varchar2(40),
	TRGLOP char(5),
	SISO int,
	MAGVCN char(4)
)

ALTER TABLE LOP ADD
CONSTRAINT FK_L_GV FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV);

CREATE TABLE HOCVIEN
(
	MAHV char(5) PRIMARY KEY,
	HO varchar2(40),
	TEN varchar2(10),
	NGSINH date,
	GIOITINH varchar2(3),
	NOISINH varchar2(40),
	MALOP char(3)
)

ALTER TABLE HOCVIEN ADD
CONSTRAINT FK_HV_L FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);

ALTER TABLE LOP ADD
CONSTRAINT FK_LOP FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV);

CREATE TABLE GIANGDAY
(
	MALOP char(3) NOT NULL,
	MAMH varchar2(10) NOT NULL,
	MAGV char(4),
	HOCKY int,
	NAM smallint,
	TUNGAY date,
	DENNGAY date
)

ALTER TABLE GIANGDAY ADD
CONSTRAINT FK_GD_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);

ALTER TABLE GIANGDAY ADD
CONSTRAINT PK_GD PRIMARY KEY (MALOP,MAMH);
ALTER TABLE GIANGDAY ADD
CONSTRAINT FK_GD1 FOREIGN KEY (MALOP) REFERENCES LOP;
ALTER TABLE GIANGDAY ADD
CONSTRAINT FK_GD2 FOREIGN KEY (MAMH) REFERENCES MONHOC;

CREATE TABLE KETQUATHI 
(
	MAHV char(5) NOT NULL,
	MAMH varchar2(10) NOT NULL,
	LANTHI int NOT NULL,
	NGTHI date,
	DIEM numeric(4,2),
	KQUA varchar2(10)
)

ALTER TABLE KETQUATHI ADD
CONSTRAINT PK_KQ PRIMARY KEY (MAMH,MAHV,LANTHI);
ALTER TABLE KETQUATHI ADD
CONSTRAINT FK_KQ1 FOREIGN KEY (MAHV) REFERENCES HOCVIEN;
ALTER TABLE KETQUATHI ADD
CONSTRAINT FK_KQ2 FOREIGN KEY (MAMH) REFERENCES MONHOC;